#!/bin/bash

sudo /usr/bin/apt-get update > /dev/null 2>&1; echo "THE EXIT CODE FOR UPDATE: $?"

sudo /usr/bin/apt dist-upgrade -y > /dev/null 2>&1; echo "THE EXIT CODE FOR UPGRADE: $?"

sudo /usr/bin/apt -y autoremove > /dev/null 2>&1; echo "THE EXIT CODE FOR AUTOREMOVE: $?"

sudo /usr/bin/apt autoclean > /dev/null 2>&1; echo "THE EXIT CODE FOR AUTOCLEAN: $?"

